

services:
  app1:
    build:
      context: ./app1  # Указываем директорию с Dockerfile для app1
    container_name: app1_container
    ports:
      - "8080:8080"
    volumes:
      - ./database:/app1/database  # Монтируем базу данных в контейнер
    networks:
      - app-network

networks:
  app-network:
    driver: bridge