# Используем базовый образ с компилятором GCC
FROM gcc:11

# Установка зависимостей
RUN apt-get update && apt-get install -y cmake

# Копирование исходного кода в контейнер
COPY . /app
WORKDIR /app

# Сборка проекта с помощью CMake
RUN cmake . && make

# Указываем команду для запуска контейнера
CMD ["./app1"]
