

services:
  todoapp:
    build: .
    volumes:
      - ./database:/app1/database
    ports:
      - "8080:8080"
    environment:
      - DB_FILE=/app1/database/base.txt  # Указываем путь к файлу внутри контейнера
    command: ["./todoapp"]  # Запуск вашего приложения
