version: "3.9"
services:
  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    container_name: app1-container

  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    container_name: app2-container
    ports:
      - "8080:80"
