services:
  app1:
    build:
      context: ./app1
    container_name: app1_container
    ports:
      - "8081:8080"

  database:
    build:
      context: ./database
    container_name: database_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
