services:
  todoapp:
    build: .
    volumes:
      - ./database:/app/database  # Монтируем папку database на хосте в контейнер
    ports:
      - "8080:8080"
    environment:
      - DB_FILE=/app/database/base.txt  # Указание на путь файла внутри контейнера
    command: ["./todoapp"]  # Запуск приложения
