version: '3.8'

services:
  app1:
    build:
      context: ./app1
    container_name: app1_container
    ports:
      - "8081:8080"

  app2:
    build:
      context: ./app2
    container_name: app2_container
    ports:
      - "8082:8080"
