name: CI for TodoApp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Compose
        run: |
          sudo apt-get install docker-compose

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Run Docker Compose
        run: |
          docker-compose up --abort-on-container-exit --exit-code-from todoapp
